// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: authorizationCommandService.proto

package nowin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationCommandAuthorizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthorizationCommandAuthorizeRequest) Reset() {
	*x = AuthorizationCommandAuthorizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authorizationCommandService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationCommandAuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationCommandAuthorizeRequest) ProtoMessage() {}

func (x *AuthorizationCommandAuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorizationCommandService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationCommandAuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationCommandAuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_authorizationCommandService_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationCommandAuthorizeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthorizationCommandAuthorizeRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthorizationCommandAuthorizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JwtToken  string `protobuf:"bytes,1,opt,name=jwtToken,proto3" json:"jwtToken,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
}

func (x *AuthorizationCommandAuthorizeResponse) Reset() {
	*x = AuthorizationCommandAuthorizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authorizationCommandService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationCommandAuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationCommandAuthorizeResponse) ProtoMessage() {}

func (x *AuthorizationCommandAuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorizationCommandService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationCommandAuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationCommandAuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_authorizationCommandService_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizationCommandAuthorizeResponse) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *AuthorizationCommandAuthorizeResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AuthorizationCommandAuthorizeResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

var File_authorizationCommandService_proto protoreflect.FileDescriptor

var file_authorizationCommandService_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x22, 0x58, 0x0a, 0x24, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x7d, 0x0a, 0x25, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x32, 0x87, 0x01, 0x0a, 0x1b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x68, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x12, 0x2b, 0x2e, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e,
	0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a,
	0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x66, 0x74,
	0x69, 0x61, 0x2d, 0x69, 0x6e, 0x63, 0x2f, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x2d, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authorizationCommandService_proto_rawDescOnce sync.Once
	file_authorizationCommandService_proto_rawDescData = file_authorizationCommandService_proto_rawDesc
)

func file_authorizationCommandService_proto_rawDescGZIP() []byte {
	file_authorizationCommandService_proto_rawDescOnce.Do(func() {
		file_authorizationCommandService_proto_rawDescData = protoimpl.X.CompressGZIP(file_authorizationCommandService_proto_rawDescData)
	})
	return file_authorizationCommandService_proto_rawDescData
}

var file_authorizationCommandService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authorizationCommandService_proto_goTypes = []interface{}{
	(*AuthorizationCommandAuthorizeRequest)(nil),  // 0: nowin.AuthorizationCommandAuthorizeRequest
	(*AuthorizationCommandAuthorizeResponse)(nil), // 1: nowin.AuthorizationCommandAuthorizeResponse
}
var file_authorizationCommandService_proto_depIdxs = []int32{
	0, // 0: nowin.AuthorizationCommandService.Authorize:input_type -> nowin.AuthorizationCommandAuthorizeRequest
	1, // 1: nowin.AuthorizationCommandService.Authorize:output_type -> nowin.AuthorizationCommandAuthorizeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authorizationCommandService_proto_init() }
func file_authorizationCommandService_proto_init() {
	if File_authorizationCommandService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authorizationCommandService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizationCommandAuthorizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authorizationCommandService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizationCommandAuthorizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authorizationCommandService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authorizationCommandService_proto_goTypes,
		DependencyIndexes: file_authorizationCommandService_proto_depIdxs,
		MessageInfos:      file_authorizationCommandService_proto_msgTypes,
	}.Build()
	File_authorizationCommandService_proto = out.File
	file_authorizationCommandService_proto_rawDesc = nil
	file_authorizationCommandService_proto_goTypes = nil
	file_authorizationCommandService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthorizationCommandServiceClient is the client API for AuthorizationCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthorizationCommandServiceClient interface {
	Authorize(ctx context.Context, in *AuthorizationCommandAuthorizeRequest, opts ...grpc.CallOption) (*AuthorizationCommandAuthorizeResponse, error)
}

type authorizationCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationCommandServiceClient(cc grpc.ClientConnInterface) AuthorizationCommandServiceClient {
	return &authorizationCommandServiceClient{cc}
}

func (c *authorizationCommandServiceClient) Authorize(ctx context.Context, in *AuthorizationCommandAuthorizeRequest, opts ...grpc.CallOption) (*AuthorizationCommandAuthorizeResponse, error) {
	out := new(AuthorizationCommandAuthorizeResponse)
	err := c.cc.Invoke(ctx, "/nowin.AuthorizationCommandService/Authorize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationCommandServiceServer is the server API for AuthorizationCommandService service.
type AuthorizationCommandServiceServer interface {
	Authorize(context.Context, *AuthorizationCommandAuthorizeRequest) (*AuthorizationCommandAuthorizeResponse, error)
}

// UnimplementedAuthorizationCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthorizationCommandServiceServer struct {
}

func (*UnimplementedAuthorizationCommandServiceServer) Authorize(context.Context, *AuthorizationCommandAuthorizeRequest) (*AuthorizationCommandAuthorizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorize not implemented")
}

func RegisterAuthorizationCommandServiceServer(s *grpc.Server, srv AuthorizationCommandServiceServer) {
	s.RegisterService(&_AuthorizationCommandService_serviceDesc, srv)
}

func _AuthorizationCommandService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationCommandAuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationCommandServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nowin.AuthorizationCommandService/Authorize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationCommandServiceServer).Authorize(ctx, req.(*AuthorizationCommandAuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthorizationCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nowin.AuthorizationCommandService",
	HandlerType: (*AuthorizationCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _AuthorizationCommandService_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authorizationCommandService.proto",
}
