// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: hostVerifyCommand.proto

package nowin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostGroupVerifyCommandVerifyByEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *HostGroupVerifyCommandVerifyByEmailRequest) Reset() {
	*x = HostGroupVerifyCommandVerifyByEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostVerifyCommand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostGroupVerifyCommandVerifyByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostGroupVerifyCommandVerifyByEmailRequest) ProtoMessage() {}

func (x *HostGroupVerifyCommandVerifyByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostVerifyCommand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostGroupVerifyCommandVerifyByEmailRequest.ProtoReflect.Descriptor instead.
func (*HostGroupVerifyCommandVerifyByEmailRequest) Descriptor() ([]byte, []int) {
	return file_hostVerifyCommand_proto_rawDescGZIP(), []int{0}
}

func (x *HostGroupVerifyCommandVerifyByEmailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HostGroupVerifyCommandVerifyByEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostGroupUUID string `protobuf:"bytes,1,opt,name=hostGroupUUID,proto3" json:"hostGroupUUID,omitempty"`
}

func (x *HostGroupVerifyCommandVerifyByEmailResponse) Reset() {
	*x = HostGroupVerifyCommandVerifyByEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostVerifyCommand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostGroupVerifyCommandVerifyByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostGroupVerifyCommandVerifyByEmailResponse) ProtoMessage() {}

func (x *HostGroupVerifyCommandVerifyByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hostVerifyCommand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostGroupVerifyCommandVerifyByEmailResponse.ProtoReflect.Descriptor instead.
func (*HostGroupVerifyCommandVerifyByEmailResponse) Descriptor() ([]byte, []int) {
	return file_hostVerifyCommand_proto_rawDescGZIP(), []int{1}
}

func (x *HostGroupVerifyCommandVerifyByEmailResponse) GetHostGroupUUID() string {
	if x != nil {
		return x.HostGroupUUID
	}
	return ""
}

var File_hostVerifyCommand_proto protoreflect.FileDescriptor

var file_hostVerifyCommand_proto_rawDesc = []byte{
	0x0a, 0x17, 0x68, 0x6f, 0x73, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6e, 0x6f, 0x77, 0x69, 0x6e,
	0x22, 0x42, 0x0a, 0x2a, 0x48, 0x6f, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x53, 0x0a, 0x2b, 0x48, 0x6f, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x68, 0x6f, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x68, 0x6f, 0x73, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x55, 0x55, 0x49, 0x44, 0x32, 0x99, 0x01, 0x0a, 0x1d, 0x48, 0x6f,
	0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x78, 0x0a, 0x0d, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x31, 0x2e, 0x6e,
	0x6f, 0x77, 0x69, 0x6e, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x32, 0x2e, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x66, 0x74, 0x69, 0x61, 0x2d, 0x69, 0x6e, 0x63, 0x2f, 0x6e,
	0x6f, 0x77, 0x69, 0x6e, 0x2d, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x3b,
	0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hostVerifyCommand_proto_rawDescOnce sync.Once
	file_hostVerifyCommand_proto_rawDescData = file_hostVerifyCommand_proto_rawDesc
)

func file_hostVerifyCommand_proto_rawDescGZIP() []byte {
	file_hostVerifyCommand_proto_rawDescOnce.Do(func() {
		file_hostVerifyCommand_proto_rawDescData = protoimpl.X.CompressGZIP(file_hostVerifyCommand_proto_rawDescData)
	})
	return file_hostVerifyCommand_proto_rawDescData
}

var file_hostVerifyCommand_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hostVerifyCommand_proto_goTypes = []interface{}{
	(*HostGroupVerifyCommandVerifyByEmailRequest)(nil),  // 0: nowin.HostGroupVerifyCommandVerifyByEmailRequest
	(*HostGroupVerifyCommandVerifyByEmailResponse)(nil), // 1: nowin.HostGroupVerifyCommandVerifyByEmailResponse
}
var file_hostVerifyCommand_proto_depIdxs = []int32{
	0, // 0: nowin.HostGroupVerifyCommandService.VerifyByEmail:input_type -> nowin.HostGroupVerifyCommandVerifyByEmailRequest
	1, // 1: nowin.HostGroupVerifyCommandService.VerifyByEmail:output_type -> nowin.HostGroupVerifyCommandVerifyByEmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hostVerifyCommand_proto_init() }
func file_hostVerifyCommand_proto_init() {
	if File_hostVerifyCommand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hostVerifyCommand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostGroupVerifyCommandVerifyByEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostVerifyCommand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostGroupVerifyCommandVerifyByEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hostVerifyCommand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hostVerifyCommand_proto_goTypes,
		DependencyIndexes: file_hostVerifyCommand_proto_depIdxs,
		MessageInfos:      file_hostVerifyCommand_proto_msgTypes,
	}.Build()
	File_hostVerifyCommand_proto = out.File
	file_hostVerifyCommand_proto_rawDesc = nil
	file_hostVerifyCommand_proto_goTypes = nil
	file_hostVerifyCommand_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HostGroupVerifyCommandServiceClient is the client API for HostGroupVerifyCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HostGroupVerifyCommandServiceClient interface {
	VerifyByEmail(ctx context.Context, in *HostGroupVerifyCommandVerifyByEmailRequest, opts ...grpc.CallOption) (*HostGroupVerifyCommandVerifyByEmailResponse, error)
}

type hostGroupVerifyCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostGroupVerifyCommandServiceClient(cc grpc.ClientConnInterface) HostGroupVerifyCommandServiceClient {
	return &hostGroupVerifyCommandServiceClient{cc}
}

func (c *hostGroupVerifyCommandServiceClient) VerifyByEmail(ctx context.Context, in *HostGroupVerifyCommandVerifyByEmailRequest, opts ...grpc.CallOption) (*HostGroupVerifyCommandVerifyByEmailResponse, error) {
	out := new(HostGroupVerifyCommandVerifyByEmailResponse)
	err := c.cc.Invoke(ctx, "/nowin.HostGroupVerifyCommandService/VerifyByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostGroupVerifyCommandServiceServer is the server API for HostGroupVerifyCommandService service.
type HostGroupVerifyCommandServiceServer interface {
	VerifyByEmail(context.Context, *HostGroupVerifyCommandVerifyByEmailRequest) (*HostGroupVerifyCommandVerifyByEmailResponse, error)
}

// UnimplementedHostGroupVerifyCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHostGroupVerifyCommandServiceServer struct {
}

func (*UnimplementedHostGroupVerifyCommandServiceServer) VerifyByEmail(context.Context, *HostGroupVerifyCommandVerifyByEmailRequest) (*HostGroupVerifyCommandVerifyByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyByEmail not implemented")
}

func RegisterHostGroupVerifyCommandServiceServer(s *grpc.Server, srv HostGroupVerifyCommandServiceServer) {
	s.RegisterService(&_HostGroupVerifyCommandService_serviceDesc, srv)
}

func _HostGroupVerifyCommandService_VerifyByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostGroupVerifyCommandVerifyByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostGroupVerifyCommandServiceServer).VerifyByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nowin.HostGroupVerifyCommandService/VerifyByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostGroupVerifyCommandServiceServer).VerifyByEmail(ctx, req.(*HostGroupVerifyCommandVerifyByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HostGroupVerifyCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nowin.HostGroupVerifyCommandService",
	HandlerType: (*HostGroupVerifyCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyByEmail",
			Handler:    _HostGroupVerifyCommandService_VerifyByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hostVerifyCommand.proto",
}
