// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: lendingGroupCommandService.proto

package nowin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LendingGroupCommandCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName       string `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Address         string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Email           string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	TelephoneNumber string `protobuf:"bytes,4,opt,name=telephoneNumber,proto3" json:"telephoneNumber,omitempty"`
	IsEnterprise    bool   `protobuf:"varint,5,opt,name=isEnterprise,proto3" json:"isEnterprise,omitempty"`
	HomePageURL     bool   `protobuf:"varint,6,opt,name=homePageURL,proto3" json:"homePageURL,omitempty"`
}

func (x *LendingGroupCommandCreateRequest) Reset() {
	*x = LendingGroupCommandCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lendingGroupCommandService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingGroupCommandCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingGroupCommandCreateRequest) ProtoMessage() {}

func (x *LendingGroupCommandCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lendingGroupCommandService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingGroupCommandCreateRequest.ProtoReflect.Descriptor instead.
func (*LendingGroupCommandCreateRequest) Descriptor() ([]byte, []int) {
	return file_lendingGroupCommandService_proto_rawDescGZIP(), []int{0}
}

func (x *LendingGroupCommandCreateRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *LendingGroupCommandCreateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LendingGroupCommandCreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LendingGroupCommandCreateRequest) GetTelephoneNumber() string {
	if x != nil {
		return x.TelephoneNumber
	}
	return ""
}

func (x *LendingGroupCommandCreateRequest) GetIsEnterprise() bool {
	if x != nil {
		return x.IsEnterprise
	}
	return false
}

func (x *LendingGroupCommandCreateRequest) GetHomePageURL() bool {
	if x != nil {
		return x.HomePageURL
	}
	return false
}

type LendingGroupCommandCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupUUID string `protobuf:"bytes,1,opt,name=groupUUID,proto3" json:"groupUUID,omitempty"`
}

func (x *LendingGroupCommandCreateResponse) Reset() {
	*x = LendingGroupCommandCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lendingGroupCommandService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingGroupCommandCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingGroupCommandCreateResponse) ProtoMessage() {}

func (x *LendingGroupCommandCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lendingGroupCommandService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingGroupCommandCreateResponse.ProtoReflect.Descriptor instead.
func (*LendingGroupCommandCreateResponse) Descriptor() ([]byte, []int) {
	return file_lendingGroupCommandService_proto_rawDescGZIP(), []int{1}
}

func (x *LendingGroupCommandCreateResponse) GetGroupUUID() string {
	if x != nil {
		return x.GroupUUID
	}
	return ""
}

var File_lendingGroupCommandService_proto protoreflect.FileDescriptor

var file_lendingGroupCommandService_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x22, 0xe0, 0x01, 0x0a, 0x20, 0x4c, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x28, 0x0a, 0x0f,
	0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x6f,
	0x6d, 0x65, 0x50, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x68, 0x6f, 0x6d, 0x65, 0x50, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x22, 0x41, 0x0a, 0x21,
	0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x55, 0x55, 0x49, 0x44, 0x32,
	0x7b, 0x0a, 0x1a, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a,
	0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x27, 0x2e, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x2e,
	0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x2e, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x66, 0x74, 0x69,
	0x61, 0x2d, 0x69, 0x6e, 0x63, 0x2f, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x2d, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lendingGroupCommandService_proto_rawDescOnce sync.Once
	file_lendingGroupCommandService_proto_rawDescData = file_lendingGroupCommandService_proto_rawDesc
)

func file_lendingGroupCommandService_proto_rawDescGZIP() []byte {
	file_lendingGroupCommandService_proto_rawDescOnce.Do(func() {
		file_lendingGroupCommandService_proto_rawDescData = protoimpl.X.CompressGZIP(file_lendingGroupCommandService_proto_rawDescData)
	})
	return file_lendingGroupCommandService_proto_rawDescData
}

var file_lendingGroupCommandService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lendingGroupCommandService_proto_goTypes = []interface{}{
	(*LendingGroupCommandCreateRequest)(nil),  // 0: nowin.LendingGroupCommandCreateRequest
	(*LendingGroupCommandCreateResponse)(nil), // 1: nowin.LendingGroupCommandCreateResponse
}
var file_lendingGroupCommandService_proto_depIdxs = []int32{
	0, // 0: nowin.LendingGroupCommandService.Create:input_type -> nowin.LendingGroupCommandCreateRequest
	1, // 1: nowin.LendingGroupCommandService.Create:output_type -> nowin.LendingGroupCommandCreateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lendingGroupCommandService_proto_init() }
func file_lendingGroupCommandService_proto_init() {
	if File_lendingGroupCommandService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lendingGroupCommandService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingGroupCommandCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lendingGroupCommandService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LendingGroupCommandCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lendingGroupCommandService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lendingGroupCommandService_proto_goTypes,
		DependencyIndexes: file_lendingGroupCommandService_proto_depIdxs,
		MessageInfos:      file_lendingGroupCommandService_proto_msgTypes,
	}.Build()
	File_lendingGroupCommandService_proto = out.File
	file_lendingGroupCommandService_proto_rawDesc = nil
	file_lendingGroupCommandService_proto_goTypes = nil
	file_lendingGroupCommandService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LendingGroupCommandServiceClient is the client API for LendingGroupCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LendingGroupCommandServiceClient interface {
	Create(ctx context.Context, in *LendingGroupCommandCreateRequest, opts ...grpc.CallOption) (*LendingGroupCommandCreateResponse, error)
}

type lendingGroupCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLendingGroupCommandServiceClient(cc grpc.ClientConnInterface) LendingGroupCommandServiceClient {
	return &lendingGroupCommandServiceClient{cc}
}

func (c *lendingGroupCommandServiceClient) Create(ctx context.Context, in *LendingGroupCommandCreateRequest, opts ...grpc.CallOption) (*LendingGroupCommandCreateResponse, error) {
	out := new(LendingGroupCommandCreateResponse)
	err := c.cc.Invoke(ctx, "/nowin.LendingGroupCommandService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LendingGroupCommandServiceServer is the server API for LendingGroupCommandService service.
type LendingGroupCommandServiceServer interface {
	Create(context.Context, *LendingGroupCommandCreateRequest) (*LendingGroupCommandCreateResponse, error)
}

// UnimplementedLendingGroupCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLendingGroupCommandServiceServer struct {
}

func (*UnimplementedLendingGroupCommandServiceServer) Create(context.Context, *LendingGroupCommandCreateRequest) (*LendingGroupCommandCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterLendingGroupCommandServiceServer(s *grpc.Server, srv LendingGroupCommandServiceServer) {
	s.RegisterService(&_LendingGroupCommandService_serviceDesc, srv)
}

func _LendingGroupCommandService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LendingGroupCommandCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LendingGroupCommandServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nowin.LendingGroupCommandService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LendingGroupCommandServiceServer).Create(ctx, req.(*LendingGroupCommandCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LendingGroupCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nowin.LendingGroupCommandService",
	HandlerType: (*LendingGroupCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _LendingGroupCommandService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lendingGroupCommandService.proto",
}
