// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: roomCommandService.proto

package nowin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomCommandCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceUUID      string                                   `protobuf:"bytes,1,opt,name=placeUUID,proto3" json:"placeUUID,omitempty"`
	RoomTypeName   string                                   `protobuf:"bytes,2,opt,name=roomTypeName,proto3" json:"roomTypeName,omitempty"`
	AbleStayNumber string                                   `protobuf:"bytes,3,opt,name=ableStayNumber,proto3" json:"ableStayNumber,omitempty"`
	StayAbleInfo   []*RoomCommandCreateRequest_StayAbleInfo `protobuf:"bytes,4,rep,name=stayAbleInfo,proto3" json:"stayAbleInfo,omitempty"`
	AmenityUUIDs   []string                                 `protobuf:"bytes,5,rep,name=amenityUUIDs,proto3" json:"amenityUUIDs,omitempty"`
}

func (x *RoomCommandCreateRequest) Reset() {
	*x = RoomCommandCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomCommandService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomCommandCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCommandCreateRequest) ProtoMessage() {}

func (x *RoomCommandCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roomCommandService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCommandCreateRequest.ProtoReflect.Descriptor instead.
func (*RoomCommandCreateRequest) Descriptor() ([]byte, []int) {
	return file_roomCommandService_proto_rawDescGZIP(), []int{0}
}

func (x *RoomCommandCreateRequest) GetPlaceUUID() string {
	if x != nil {
		return x.PlaceUUID
	}
	return ""
}

func (x *RoomCommandCreateRequest) GetRoomTypeName() string {
	if x != nil {
		return x.RoomTypeName
	}
	return ""
}

func (x *RoomCommandCreateRequest) GetAbleStayNumber() string {
	if x != nil {
		return x.AbleStayNumber
	}
	return ""
}

func (x *RoomCommandCreateRequest) GetStayAbleInfo() []*RoomCommandCreateRequest_StayAbleInfo {
	if x != nil {
		return x.StayAbleInfo
	}
	return nil
}

func (x *RoomCommandCreateRequest) GetAmenityUUIDs() []string {
	if x != nil {
		return x.AmenityUUIDs
	}
	return nil
}

type RoomCommandCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoomCommandCreateResponse) Reset() {
	*x = RoomCommandCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomCommandService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomCommandCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCommandCreateResponse) ProtoMessage() {}

func (x *RoomCommandCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roomCommandService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCommandCreateResponse.ProtoReflect.Descriptor instead.
func (*RoomCommandCreateResponse) Descriptor() ([]byte, []int) {
	return file_roomCommandService_proto_rawDescGZIP(), []int{1}
}

type RoomCommandCreateRequest_StayAbleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *RoomCommandCreateRequest_StayAbleInfo) Reset() {
	*x = RoomCommandCreateRequest_StayAbleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomCommandService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomCommandCreateRequest_StayAbleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCommandCreateRequest_StayAbleInfo) ProtoMessage() {}

func (x *RoomCommandCreateRequest_StayAbleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_roomCommandService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCommandCreateRequest_StayAbleInfo.ProtoReflect.Descriptor instead.
func (*RoomCommandCreateRequest_StayAbleInfo) Descriptor() ([]byte, []int) {
	return file_roomCommandService_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RoomCommandCreateRequest_StayAbleInfo) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *RoomCommandCreateRequest_StayAbleInfo) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_roomCommandService_proto protoreflect.FileDescriptor

var file_roomCommandService_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6e, 0x6f, 0x77, 0x69,
	0x6e, 0x22, 0xba, 0x02, 0x0a, 0x18, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x55, 0x55, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c,
	0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x79, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x50, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x79,
	0x41, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x53, 0x74, 0x61, 0x79, 0x41, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x73, 0x74,
	0x61, 0x79, 0x41, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6d,
	0x65, 0x6e, 0x69, 0x74, 0x79, 0x55, 0x55, 0x49, 0x44, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x6d, 0x65, 0x6e, 0x69, 0x74, 0x79, 0x55, 0x55, 0x49, 0x44, 0x73, 0x1a, 0x3e,
	0x0a, 0x0c, 0x53, 0x74, 0x61, 0x79, 0x41, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1b,
	0x0a, 0x19, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x63, 0x0a, 0x12, 0x52,
	0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4d, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x6e, 0x6f,
	0x77, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6e,
	0x6f, 0x77, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x6f, 0x66, 0x74, 0x69, 0x61, 0x2d, 0x69, 0x6e, 0x63, 0x2f, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x2d,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x6e, 0x6f, 0x77, 0x69, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_roomCommandService_proto_rawDescOnce sync.Once
	file_roomCommandService_proto_rawDescData = file_roomCommandService_proto_rawDesc
)

func file_roomCommandService_proto_rawDescGZIP() []byte {
	file_roomCommandService_proto_rawDescOnce.Do(func() {
		file_roomCommandService_proto_rawDescData = protoimpl.X.CompressGZIP(file_roomCommandService_proto_rawDescData)
	})
	return file_roomCommandService_proto_rawDescData
}

var file_roomCommandService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_roomCommandService_proto_goTypes = []interface{}{
	(*RoomCommandCreateRequest)(nil),              // 0: nowin.RoomCommandCreateRequest
	(*RoomCommandCreateResponse)(nil),             // 1: nowin.RoomCommandCreateResponse
	(*RoomCommandCreateRequest_StayAbleInfo)(nil), // 2: nowin.RoomCommandCreateRequest.StayAbleInfo
}
var file_roomCommandService_proto_depIdxs = []int32{
	2, // 0: nowin.RoomCommandCreateRequest.stayAbleInfo:type_name -> nowin.RoomCommandCreateRequest.StayAbleInfo
	0, // 1: nowin.RoomCommandService.Create:input_type -> nowin.RoomCommandCreateRequest
	1, // 2: nowin.RoomCommandService.Create:output_type -> nowin.RoomCommandCreateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_roomCommandService_proto_init() }
func file_roomCommandService_proto_init() {
	if File_roomCommandService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_roomCommandService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomCommandCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomCommandService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomCommandCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomCommandService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomCommandCreateRequest_StayAbleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roomCommandService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roomCommandService_proto_goTypes,
		DependencyIndexes: file_roomCommandService_proto_depIdxs,
		MessageInfos:      file_roomCommandService_proto_msgTypes,
	}.Build()
	File_roomCommandService_proto = out.File
	file_roomCommandService_proto_rawDesc = nil
	file_roomCommandService_proto_goTypes = nil
	file_roomCommandService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RoomCommandServiceClient is the client API for RoomCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoomCommandServiceClient interface {
	Create(ctx context.Context, in *RoomCommandCreateRequest, opts ...grpc.CallOption) (*RoomCommandCreateResponse, error)
}

type roomCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomCommandServiceClient(cc grpc.ClientConnInterface) RoomCommandServiceClient {
	return &roomCommandServiceClient{cc}
}

func (c *roomCommandServiceClient) Create(ctx context.Context, in *RoomCommandCreateRequest, opts ...grpc.CallOption) (*RoomCommandCreateResponse, error) {
	out := new(RoomCommandCreateResponse)
	err := c.cc.Invoke(ctx, "/nowin.RoomCommandService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomCommandServiceServer is the server API for RoomCommandService service.
type RoomCommandServiceServer interface {
	Create(context.Context, *RoomCommandCreateRequest) (*RoomCommandCreateResponse, error)
}

// UnimplementedRoomCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRoomCommandServiceServer struct {
}

func (*UnimplementedRoomCommandServiceServer) Create(context.Context, *RoomCommandCreateRequest) (*RoomCommandCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterRoomCommandServiceServer(s *grpc.Server, srv RoomCommandServiceServer) {
	s.RegisterService(&_RoomCommandService_serviceDesc, srv)
}

func _RoomCommandService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomCommandCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomCommandServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nowin.RoomCommandService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomCommandServiceServer).Create(ctx, req.(*RoomCommandCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nowin.RoomCommandService",
	HandlerType: (*RoomCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _RoomCommandService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roomCommandService.proto",
}
