name: npm publish without master
on:
  push:
    branches-ignore:
      - "master"
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
          scope: "@softia-inc"
      - run: yarn
      - run: chmod u+x version-up.sh
      - name: replace version
        run: export v=0.0.1
      - name: generate
        run: make gen-node
      - run: |
          TAG=$(echo ${{ github.ref }} | sed -e "s#refs/heads/##g")
          yarn publish --tag ${TAG}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}